# Experience yields for killing mobs. You can add additional mobs to this list
# to support new/custom mobs.
#
# These values will be ignored if the "useDroppedExp" option is enabled in config.yml.
kill:
  #
  # You can define yields per class by adding new sections here. This can be used
  # to have different classes benefit from killing certain mobs more than others.
  default:
    blaze: '10'
    cavespider: '5'
    creeper: '3'
    elderguardian: '10'
    enderdragon: '400'
    enderman: '5'
    endermite: '3'
    evoker: '10'
    ghast: '5'
    giant: '20'
    guardian: '10'
    husk: '2'
    irongolem: '10'
    magmacube: '1'
    pigzombie: '5'
    player: '5'
    shulker: '5'
    silverfish: '2'
    skeleton: '3'
    slime: '1'
    spider: '3'
    stray: '5'
    vex: '3'
    vindicator: '5'
    witch: '3'
    wither: '500'
    witherskeleton: '5'
    zombie: '2'

# These are experience values provided when a player breaks a block.
break:
  #
  # Whether or not to allow players to place a world back down and break it again
  # to get additional experience. Note that disabling this will cause all world
  # changes to be tracked in order to remember what was placed or not. Blocks
  # existing before this is disabled will not be protected from experience yields.
  allow-replace: true
  #
  # The yields per world type. You can add any world types not in this list by simply
  # appending the bukkit name of the world type. See
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  # for valid types. This list is not case-sensitive.
  types:
    #
    # You can add classes as well that allow certain blocks only to benefit
    # that class. For example, if you want a miner to benefit from ore but
    # a farmer to benefit from crops, you can add a "miner" section containing
    # the ore and a "farmer" section containing the crops. This would look something
    # like:
    #
    # # Blocks only for miners
    # miner:
    #   COAL: 1
    #   IRON_ORE: 10
    # # Blocks only for farmers
    # farmer:
    #   CROPS: 5
    default:
      COAL: 1
      QUARTZ_ORE: 1
      IRON_ORE: 10
      GOLD_ORE: 15
      REDSTONE_ORE: 20
      LAPIS_ORE: 25
      DIAMOND_ORE: 50
      EMERALD_ORE: 100
#
# Experience yields when a player places a block. There's not a built-in way to check
# for players repeatedly placing down the same block, so use this type of experience
# with caution. Works similar to break, just without the replace option.
place:
  default:
    DIAMOND_BLOCK: 1
#
# Experience yields when a player crafts items.
craft:
  #
  # Similar to above, you can specify classes to get
  # experience from different crafts.
  default:
    BOW: 5
    IRON_CHESTPLATE: 80
    IRON_LEGGINGS: 70
    IRON_HELMET: 50
    IRON_BOOTS: 40
    IRON_SWORD: 20
    IRON_AXE: 30
    GOLD_CHESTPLATE: 120
    GOLD_LEGGINGS: 105
    GOLD_HELMET: 75
    GOLD_BOOTS: 60
    GOLD_SWORD: 30
    GOLD_AXE: 45
    DIAMOND_CHESTPLATE: 400
    DIAMOND_LEGGINGS: 350
    DIAMOND_HELMET: 250
    DIAMOND_BOOTS: 200
    DIAMOND_SWORD: 100
    DIAMOND_AXE: 150